name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: boostrap
      run: bash bootstrap
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make install
      run: sudo make install
    #- name: make distcheck
    #  run: make distcheck
